import { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  // ─── HORIZONTAL PUSH ───────────────────────────────────────────────────────
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    pattern: 'horizontal_push',
    chestArea: 'mid',
    primaryMuscles: ['chest', 'front_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'incline_barbell_press',
    name: 'Incline Barbell Press',
    pattern: 'horizontal_push',
    chestArea: 'upper',
    primaryMuscles: ['chest', 'front_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    pattern: 'horizontal_push',
    chestArea: 'mid',
    primaryMuscles: ['chest', 'front_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'incline_db_press',
    name: 'Incline Dumbbell Press',
    pattern: 'horizontal_push',
    chestArea: 'upper',
    primaryMuscles: ['chest', 'front_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'push_up',
    name: 'Push-Up',
    pattern: 'horizontal_push',
    chestArea: 'mid',
    primaryMuscles: ['chest', 'front_delt'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'decline_push_up',
    name: 'Decline Push-Up',
    pattern: 'horizontal_push',
    chestArea: 'lower',
    primaryMuscles: ['chest', 'front_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'wide_push_up',
    name: 'Wide Push-Up',
    pattern: 'horizontal_push',
    chestArea: 'mid',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt', 'triceps'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },

  // ─── VERTICAL PUSH ─────────────────────────────────────────────────────────
  {
    id: 'barbell_ohp',
    name: 'Barbell Overhead Press',
    pattern: 'vertical_push',
    primaryMuscles: ['front_delt', 'side_delt'],
    secondaryMuscles: ['triceps', 'traps'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    pattern: 'vertical_push',
    primaryMuscles: ['front_delt', 'side_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    pattern: 'vertical_push',
    primaryMuscles: ['front_delt', 'side_delt'],
    secondaryMuscles: ['triceps', 'rear_delt'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'pike_push_up',
    name: 'Pike Push-Up',
    pattern: 'vertical_push',
    primaryMuscles: ['front_delt', 'side_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'handstand_push_up',
    name: 'Handstand Push-Up',
    pattern: 'vertical_push',
    primaryMuscles: ['front_delt', 'side_delt'],
    secondaryMuscles: ['triceps', 'traps'],
    equipment: ['bodyweight'],
    isCompound: true,
  },

  // ─── HORIZONTAL PULL (rows) ─────────────────────────────────────────────────
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'tbar_row',
    name: 'T-Bar Row',
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'single_arm_db_row',
    name: 'Single-Arm Dumbbell Row',
    pattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'chest_supported_db_row',
    name: 'Chest-Supported Dumbbell Row',
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back', 'rear_delt'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['bodyweight', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'db_bent_over_row',
    name: 'Dumbbell Bent-Over Row',
    pattern: 'horizontal_pull',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },

  // ─── VERTICAL PULL ─────────────────────────────────────────────────────────
  {
    id: 'pull_up',
    name: 'Pull-Up',
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['bodyweight', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    pattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upper_back'],
    equipment: ['bodyweight', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'cable_pullover',
    name: 'Cable Straight-Arm Pulldown',
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps'],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'db_pullover',
    name: 'Dumbbell Pullover',
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['chest', 'triceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'band_assisted_pull_up',
    name: 'Band-Assisted Pull-Up',
    pattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['bodyweight'],
    isCompound: true,
  },

  // ─── SQUAT ─────────────────────────────────────────────────────────────────
  {
    id: 'barbell_back_squat',
    name: 'Barbell Back Squat',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'lower_back'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'db_lunge',
    name: 'Dumbbell Lunge',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'bw_squat',
    name: 'Bodyweight Squat',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'jump_squat',
    name: 'Jump Squat',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'core'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'step_up',
    name: 'Step-Up',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'pistol_squat',
    name: 'Pistol Squat',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['bodyweight'],
    isCompound: true,
  },

  // ─── HINGE ─────────────────────────────────────────────────────────────────
  {
    id: 'barbell_deadlift',
    name: 'Barbell Deadlift',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes', 'lower_back'],
    secondaryMuscles: ['quads', 'traps', 'core'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'barbell_rdl',
    name: 'Romanian Deadlift (Barbell)',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'core'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'db_rdl',
    name: 'Romanian Deadlift (Dumbbell)',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'barbell_hip_thrust',
    name: 'Barbell Hip Thrust',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'db_hip_thrust',
    name: 'Dumbbell Hip Thrust',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'lower_back'],
    secondaryMuscles: ['glutes'],
    equipment: ['full_gym'],
    isCompound: true,
  },
  {
    id: 'single_leg_rdl',
    name: 'Single-Leg RDL',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'core'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: true,
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Hamstring Curl',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight', 'full_gym'],
    isCompound: false,
  },

  // ─── ACCESSORIES ───────────────────────────────────────────────────────────

  // Biceps
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    pattern: 'accessory',
    accessoryCategory: 'biceps',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'db_curl',
    name: 'Dumbbell Curl',
    pattern: 'accessory',
    accessoryCategory: 'biceps',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    pattern: 'accessory',
    accessoryCategory: 'biceps',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    pattern: 'accessory',
    accessoryCategory: 'biceps',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'incline_db_curl',
    name: 'Incline Dumbbell Curl',
    pattern: 'accessory',
    accessoryCategory: 'biceps',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    pattern: 'accessory',
    accessoryCategory: 'biceps',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },

  // Triceps
  {
    id: 'cable_pushdown',
    name: 'Cable Tricep Pushdown',
    pattern: 'accessory',
    accessoryCategory: 'triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'overhead_tricep_ext',
    name: 'Overhead Tricep Extension',
    pattern: 'accessory',
    accessoryCategory: 'triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher',
    pattern: 'accessory',
    accessoryCategory: 'triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'close_grip_push_up',
    name: 'Close-Grip Push-Up',
    pattern: 'accessory',
    accessoryCategory: 'triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delt'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'diamond_push_up',
    name: 'Diamond Push-Up',
    pattern: 'accessory',
    accessoryCategory: 'triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'db_kickback',
    name: 'Dumbbell Kickback',
    pattern: 'accessory',
    accessoryCategory: 'triceps',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },

  // Side Delts
  {
    id: 'db_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    pattern: 'accessory',
    accessoryCategory: 'side_delt',
    primaryMuscles: ['side_delt'],
    secondaryMuscles: ['traps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    pattern: 'accessory',
    accessoryCategory: 'side_delt',
    primaryMuscles: ['side_delt'],
    secondaryMuscles: [],
    equipment: ['full_gym'],
    isCompound: false,
  },

  // Rear Delts
  {
    id: 'cable_face_pull',
    name: 'Cable Face Pull',
    pattern: 'accessory',
    accessoryCategory: 'rear_delt',
    primaryMuscles: ['rear_delt', 'traps'],
    secondaryMuscles: ['biceps'],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'db_rear_delt_fly',
    name: 'Dumbbell Rear Delt Fly',
    pattern: 'accessory',
    accessoryCategory: 'rear_delt',
    primaryMuscles: ['rear_delt'],
    secondaryMuscles: ['upper_back'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'band_pull_apart',
    name: 'Band Pull-Apart',
    pattern: 'accessory',
    accessoryCategory: 'rear_delt',
    primaryMuscles: ['rear_delt'],
    secondaryMuscles: ['upper_back'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'db_upright_row',
    name: 'Dumbbell Upright Row',
    pattern: 'accessory',
    accessoryCategory: 'side_delt',
    primaryMuscles: ['side_delt', 'traps'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },

  // Chest isolation
  {
    id: 'cable_chest_fly',
    name: 'Cable Chest Fly',
    pattern: 'accessory',
    accessoryCategory: 'chest_iso',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt'],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'db_chest_fly',
    name: 'Dumbbell Chest Fly',
    pattern: 'accessory',
    accessoryCategory: 'chest_iso',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },

  // Back isolation
  {
    id: 'db_pullover_iso',
    name: 'Dumbbell Pullover',
    pattern: 'accessory',
    accessoryCategory: 'back_iso',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['chest', 'triceps'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'cable_straight_arm_pulldown',
    name: 'Cable Straight-Arm Pulldown',
    pattern: 'accessory',
    accessoryCategory: 'back_iso',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps'],
    equipment: ['full_gym'],
    isCompound: false,
  },

  // Glute isolation
  {
    id: 'cable_kickback',
    name: 'Cable Glute Kickback',
    pattern: 'accessory',
    accessoryCategory: 'glute_iso',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'db_sumo_squat',
    name: 'Dumbbell Sumo Squat',
    pattern: 'accessory',
    accessoryCategory: 'glute_iso',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'donkey_kick',
    name: 'Donkey Kick',
    pattern: 'accessory',
    accessoryCategory: 'glute_iso',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },

  // Calves
  {
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    pattern: 'accessory',
    accessoryCategory: 'calves',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'seated_calf_raise',
    name: 'Seated Calf Raise',
    pattern: 'accessory',
    accessoryCategory: 'calves',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['full_gym'],
    isCompound: false,
  },
  {
    id: 'single_leg_calf_raise',
    name: 'Single-Leg Calf Raise',
    pattern: 'accessory',
    accessoryCategory: 'calves',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },

  // Core
  {
    id: 'plank',
    name: 'Plank',
    pattern: 'accessory',
    accessoryCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['lower_back'],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    pattern: 'accessory',
    accessoryCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    pattern: 'accessory',
    accessoryCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['core'],
    equipment: ['bodyweight', 'full_gym'],
    isCompound: false,
  },
  {
    id: 'ab_wheel',
    name: 'Ab Wheel Rollout',
    pattern: 'accessory',
    accessoryCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['lower_back'],
    equipment: ['full_gym'],
    isCompound: false,
  },
];

export function getExercisesForEquipment(
  equipment: import('./types').Equipment
): Exercise[] {
  return EXERCISES.filter((ex) => ex.equipment.includes(equipment));
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((ex) => ex.id === id);
}
